require('dashboard').setup({
  theme = 'doom',
  config = {
    header = {
      '',
      ' ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣤⠇⠀⠀⠀⠀⠀⠀⠀⠀',
      ' ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⡾⠋⠀⠀⠀⠀⠀⠀⠀⣠⡆⠀',
      ' ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⠰⠁⠀⢀⠀⠀⣿⣧⡔⠀⠀⠀⠀⠀⠀⣰⠟⠁⠀',
      ' ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣧⡀⠀⡀⢹⣄⣠⣿⣿⡧⣾⠀⣀⠀⡀⠀⠀⠀⠀⠀',
      ' ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢹⡇⢀⣿⣿⣿⣿⣿⡏⡀⠋⣰⡇⠞⡀⠀⠀⠀⣠⠖',
      ' ⠀⠀⠀⠀⠀⢦⡀⠀⠀⠐⣸⣴⣸⣿⣿⣿⣿⣿⢴⣧⣴⣿⠃⣰⡟⠀⡜⠀⠁⠀',
      ' ⢠⡀⠀⢄⢠⠈⢿⡄⣆⡇⢿⣿⣿⣿⡿⡇⢏⣴⢸⡿⠁⡇⣰⠋⡀⠀⡇⠀⠀⠀',
      ' ⠀⠻⡄⠸⣾⠧⡘⡇⠸⣿⣼⣧⡈⣮⣾⣷⣿⠣⣫⣷⣶⡇⡇⣦⡇⠐⠁⠀⠀⠀',
      ' ⡀⠀⠀⡀⢈⡼⠾⠾⠇⡿⣎⣿⣿⡿⡿⣿⣿⣴⡿⠟⠋⢷⢣⢟⠀⠀⠀⠀⠀⠀',
      ' ⠘⠀⢀⢹⡆⠦⢰⢋⢝⠁⠟⣵⢻⣇⢧⣿⣿⠟⡁⠀⠀⣾⢸⢸⠁⠀⠀⠀⠀⠀',
      ' ⠀⠀⠀⢋⣷⡉⢘⠤⠥⡶⠁⡶⢿⣿⣷⡦⢀⠈⠁⠀⣠⣧⡇⡎⠀⠀⠀⠀⠀⠀',
      ' ⠀⠀⠀⠘⢿⢘⡲⠬⠭⠶⢠⠐⣡⢹⣷⡿⡕⢝⣒⣫⠶⣻⠃⣄⠀⠀⠀⠀⠀⠀',
      ' ⠀⠀⠀⠑⢠⡁⠪⠉⠉⣴⢢⡗⠴⢟⣿⢳⠙⠶⣤⣤⠞⣡⡳⡜⡆⠀⠀⠀⠀⠀',
      ' ⠀⠀⠀⠀⠀⠁⠀⠀⠘⡇⠾⠥⠃⢛⣋⣩⢞⣓⡺⡿⠘⢗⣕⡚⠁⠀⠀⠀⠀⠀',
      ' ⠀⠀⠀⠀⠀⠀⣀⣤⣾⠇⡁⢁⠁⠈⠉⡁⢈⠛⠿⣿⣄⡀⠉⠀⠀⠀⠀⠀⠀⠀',
      ' ⠀⠀⠀⠀⠀⠈⠉⠁⢲⣆⣛⡵⢛⣛⣛⢯⣛⣀⣶⠊⠉⠁⠀⠀⠀⠀⠀⠀⠀⠀',
      ' ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠛⠱⠢⣿⡿⣿⡗⠎⠛⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀',
      '                               ',
      '',
    }, --your header
    center = {
      {
        icon = '  ',
        desc = 'Update Plugins                          ',
        shortcut = 'SPC p u',
        action = 'Lazy update',
      },
      {
        icon = '  ',
        desc = 'Recently opened files                   ',
        action = 'Telescope oldfiles',
        shortcut = 'SPC f h',
      },
      {
        icon = '  ',
        desc = 'Find  File                              ',
        action = 'Telescope find_files find_command=rg,--hidden,--files',
        shortcut = 'SPC f f',
      },
      {
        icon = '  ',
        desc = 'File Browser                            ',
        action = 'NvimTreeToggle',
        shortcut = 'SPC   e',
      },
      {
        icon = '  ',
        desc = 'Find  word                              ',
        action = 'Telescope live_grep',
        shortcut = 'SPC f b',
      },
      {
        icon = '  ',
        desc = 'Open Personal dotfiles                  ',
        action = 'Telescope dotfiles path=' .. vim.env.HOME .. '/.dotfiles',
        shortcut = 'SPC f d',
      },
      {
        icon = '  ',
        desc = 'Restore the last session                ',
        action = "lua require('persistence').load({last=true})",
        shortcut = 'SPC s l',
      },
    },
    footer = {},
  },
})
